{{- if or .Values.storage.s3 .Values.storage.azure -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "backup.fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if .Values.storage.s3 }}
  s3-cloud-storage-key: {{ printf "%s:%s" .Values.storage.s3.accessKey .Values.storage.s3.secretKey | b64enc | quote }}
{{- end }}
{{- if .Values.storage.azure }}
  azure-cloud-storage-key: {{ printf "%s:%s" .Values.storage.azure.accountName .Values.storage.azure.accountKey | b64enc | quote }}
{{- end }}
{{- end -}}